name: MATLAB Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Run MATLAB Tests
        run: |
          matlab -batch "addpath(pwd); \
                        results = runtests('TU_A'); \
                        disp(results); \
                        if any(~[results.Passed]); \
                            fprintf('::error file=%s,line=%d::%s\n','TU_A.m',1,'MATLAB Unit Test Failed: RiseTime or Overshoot exceeded limit'); \
                            exit(1); \
                        end"
