name: MATLAB Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup MATLAB
      uses: matlab-actions/setup-matlab@v1

    - name: Run Unit Tests
      run: |
        matlab -batch "disp('Running MATLAB unit tests...'); \
                      addpath(pwd); \
                      results = runtests(''); \
                      disp(results); \
                      assert(all([results.Passed]), 'One or more MATLAB tests failed!')"
